apiVersion: v1
kind: Service
metadata:
  name: user-profile-management
  labels:
    app: user-profile-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user-profile-management