---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile-management
  labels:
    app: user-profile-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-profile-management
  template:
    metadata:
      labels:
        app: user-profile-management
    spec:
      containers:
        - name: user-profile-management
          image: username/user-profile-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dating-coordinator
  labels:
    app: dating-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dating-coordinator
  template:
    metadata:
      labels:
        app: dating-coordinator
    spec:
      containers:
        - name: dating-coordinator
          image: username/dating-coordinator:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-algorithm
  labels:
    app: matching-algorithm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-algorithm
  template:
    metadata:
      labels:
        app: matching-algorithm
    spec:
      containers:
        - name: matching-algorithm
          image: username/matching-algorithm:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: user-profile-management
  labels:
    app: user-profile-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user-profile-management


---


apiVersion: v1
kind: Service
metadata:
  name: dating-coordinator
  labels:
    app: dating-coordinator
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: dating-coordinator


---


apiVersion: v1
kind: Service
metadata:
  name: matching-algorithm
  labels:
    app: matching-algorithm
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: matching-algorithm

